version: "3.9"

services:
  postgres:
    image: postgres:13-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

  si8cloud-console-be:
    image: cloud.canister.io:5000/flaviosi8/si8cloud-console-be:0.4
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/code
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8000:8000
    depends_on:
      - postgres
    env_file:
      - .env
    deploy:
      placement:
        constraints: [node.hostname == docker-ce-ubuntu-dev02 ]

  si8cloud-console-fe:
    image: cloud.canister.io:5000/flaviosi8/si8cloud-console-fe:0.4
    command: nginx
    ports:
      - 8080:8080
    depends_on:
      - si8cloud-console-be

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@local.com
      - PGADMIN_DEFAULT_PASSWORD=secret
      - PGADMIN_LISTEN_PORT=80
    ports:
      - 80:80
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
