version: "3.9"

services:

  proxy-server-nginx:
    image: nginx:stable
    ports:
      - 8080:8080
    volumes:
      - "${PATH_NGINX_CONF}/nginx.conf:/etc/nginx/nginx.conf"

  postgres:
    image: postgres:13-alpine
    volumes:
      - ${POSTGRES_DATA_DIR}:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    user: 1000:1000
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@local.com
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
      - PGADMIN_LISTEN_PORT=80
      - CONFIG_DATABASE_URI=postgresql://pgadmin:pgadmin@postgres:5432/pgadmin
    ports:
      - 80:80
    depends_on:
      - postgres

  si8cloud-console-be:
    image: cloud.canister.io:5000/flaviosi8/si8cloud-console-be:latest
    environment:
      - DB_HOST=postgres
      - DB_NAME=${POSTGRES_DB}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_USER=${POSTGRES_USER}
      - DB_PORT=5432
      - SECRET_KEY=loremipsum
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - postgres
    deploy:
      placement:
        constraints: [node.hostname == docker-ce-ubuntu-dev02 ]
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  si8cloud-console-fe:
    image: cloud.canister.io:5000/flaviosi8/si8cloud-console-fe:0.4
    command: nginx
    depends_on:
      - si8cloud-console-be
