version: "3.9"

services:
  postgres:
    image: postgres:13-alpine
    volumes:
      - ${POSTGRES_DATA_DIR}:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@local.com
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
      - PGADMIN_LISTEN_PORT=80
    ports:
      - 80:80
    depends_on:
      - postgres
    volumes:
      - ${PGADMIN_DATA_DIR}:/var/lib/pgadmin

  si8cloud-console-be:
    image: cloud.canister.io:5000/flaviosi8/si8cloud-console-be:latest
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8000:8000
    depends_on:
      - postgres
    deploy:
      placement:
        constraints: [node.hostname == docker-ce-ubuntu-dev02 ]

  si8cloud-console-fe:
    image: cloud.canister.io:5000/flaviosi8/si8cloud-console-fe:0.4
    command: nginx
    ports:
      - 8080:8080
    depends_on:
      - si8cloud-console-be
